---
language: python

python:
  - "2.7"

install:
  - pip install ansible ansible-lint molecule

script:
  - molecule --debug lint
  - molecule --debug syntax

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
