---
collections:
- name: community.crypto
  version: 2.11.0
- name: community.docker
  version: 3.4.2
- name: community.general
  version: 6.4.0
- name: ansible.posix
  version: 1.5.1
- name: community.windows
  version: 1.13.0
