---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ROLES_PATH='${MOLECULE_PROJECT_DIRECTORY}/..'
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: ultral/docker_centos_ansible_tests:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible
